spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bambino?useSSL=false
    username: root
    password: S4nt4T3ch2017
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    org:
      springframework:
        web: error